name: 'Setup AMXXPawn Compiler'
author: 'rumblefrog'
description: 'Install and setup AMXXPawn compiler'
inputs:
  version:
    description: 'Version of AMXX compiler'
    required: true
    default: '1.10.x'
  version-file:
    description: 'File to parse to get the version of the plugin'
    required: false
    default: ''
  define-name:
    description: 'Name of the define for the version of the plugin if you are using one'
    required: false
    default: ''
  no-amxxpc-proxy:
    description: 'Whether amxxpc should not be proxied to fix relative include path'
    required: false
    default: 'false'
outputs:
  version:
    description: 'Version of the AMXX compiler used'
  version-file:
    description: 'Version of the .sma file'
runs:
  using: 'node16'
  main: 'lib/index.js'
branding:
  icon: 'command'  
  color: 'blue'