name: Development Workflow

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  run:
    name: Run action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup AMXXPawn Compiler
      uses: ./
      with:
        version: "1.10.x"
      
    - name: Verify compiler
      run: |
        which amxxpc
        echo $includePath
        ls -l $scriptingPath
        cat $(which amxxpc)
        amxxpc __tests__/compile.sma
