name: Development Workflow

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  run:
    name: Run action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup SourcePawn Compiler
      uses: ./
      with:
        version: "1.12.x"
      
    - name: Verify compiler
      run: |
        which spcomp
        echo $includePath
        ls -l $scriptingPath
        cat $(which spcomp)
        spcomp __tests__/compile.sp
